[package]
name = "batbox-diff"
description = "Easy struct diffing"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
batbox-diff-derive.workspace = true
