[package]
name = "batbox-tuple-macros"
description = "Macro for calling your macro for all tuple sizes"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
