[package]
name = "batbox-collection-derive"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
toml.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
darling.workspace = true

[lib]
proc-macro = true
